### ISSUE TITLE
[Bug]: Crash on launch when using ViaVersionPlus

### ISSUE THREAD

**Issue by pierrelasse** [senseiwells/EssentialClient#130] opened 2024-03-02 14:30 UTC
Here the log with ViaFabricPlus
[crash.txt](https://github.com/senseiwells/EssentialClient/files/14469712/crash.txt)
and here without
[working.txt](https://github.com/senseiwells/EssentialClient/files/14469714/working.txt)

ViaFabricPlus v3.0.6
Essential Client v1.4.1
Carpet Mod v1.4.128+v231205

Essential Client (not Carpet Mod) is causing the problem.

**Comment by senseiwells** [comment] 2024-03-02 19:07
Duplicate of #125

**Closed by senseiwells** 2024-03-02 19:07 UTC
